name: Install nix and resolve packages using nix-shell
on:
  workflow_dispatch:
  push:
    branches:
      - main
jobs:
  install-nix-and-use-nix-shell:
    runs-on: ubuntu-24.04
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: Install nix and use nix shell
        run: |
          curl -L https://nixos.org/nix/install | sh -s -- --daemon --yes

          if [ -e '/nix/var/nix/profiles/default/etc/profile.d/nix-daemon.sh' ]; then
            . '/nix/var/nix/profiles/default/etc/profile.d/nix-daemon.sh'
          fi

          # Testing whether Nix is available in subsequent commands
          nix --version

          nix-shell -p bash kubectl helm helmfile k9s

          kubectl version || true

          exit 0

  install-linuxbrew-and-resolve-packages:
    runs-on: ubuntu-24.04
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: Install linuxbrew and resolve packages
        run: |
          sudo apt update -y && sudo apt install -y sshpass sudo curl git openssl build-essential procps file gettext

          sudo useradd linuxbrew

          sudo usermod -aG sudo linuxbrew
          sudo usermod -aG linuxbrew linuxbrew

          sudo usermod -aG linuxbrew $USER

          export LINUXBREW_PASSWORD=$(openssl rand -hex 32)
          echo -e "$LINUXBREW_PASSWORD\n$LINUXBREW_PASSWORD\n" | sudo -E passwd linuxbrew
          sudo mkdir -p /home/linuxbrew
          sudo chown linuxbrew:linuxbrew -R /home/linuxbrew
          sudo -u linuxbrew /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
          (echo; echo 'eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)"') >> ~/.bashrc

          eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)"

          sudo chown -R runner /home/linuxbrew/.linuxbrew
          sudo chmod -R u+w /home/linuxbrew/.linuxbrew

          brew install kubectl helm helmfile k9s

          kubectl version || true
