name: Install nix and resolve packages using nix-shell
on:
  push:
    branches:
      - main
jobs:
  install-nix-and-use-nix-shell:
    runs-on: ubuntu-24.04
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: Install nix and use nix shell
        run: |
          curl -L https://nixos.org/nix/install | sh -s -- --daemon --yes

          if [ -e '/nix/var/nix/profiles/default/etc/profile.d/nix-daemon.sh' ]; then
            . '/nix/var/nix/profiles/default/etc/profile.d/nix-daemon.sh'
          fi

          # Testing whether Nix is available in subsequent commands
          nix --version

          nix-shell -p bash kubectl helm helmfile k9s
          exit 0

  install-linuxbrew-and-resolve-packages:
    runs-on: ubuntu-24.04
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: Install linuxbrew and resolve packages
        run: |
          sudo apt update -y && sudo apt install -y sshpass sudo curl git openssl build-essential procps file gettext

          sudo useradd linuxbrew
          sudo usermod -aG sudo linuxbrew
          export LINUXBREW_PASSWORD=$(openssl rand -hex 32)
          echo -e "$LINUXBREW_PASSWORD\n$LINUXBREW_PASSWORD\n" | sudo -E passwd linuxbrew
          sudo -E -u linuxbrew sudo -S -v <<< "$LINUXBREW_PASSWORD" && sudo mkdir -p /home/linuxbrew && sudo chown linuxbrew -R /home/linuxbrew && cd && /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
          (echo; echo 'eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)"') >> ~/.bashrc

          sudo bash -c 'eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)" && brew install kubectl helm helmfile k9s'
